export const RESET = "RESET"
export const ADD_ITEM = "ADD_ITEM"; 
export const FETCHED_CLOSET = "FETCHED_CLOSET"; 
export const FETCHING_CLOSET = "FETCHING_CLOSET"; 
export const FETCHED_CATEGORY = "FETCHED_CATEGORY"; 
export const FETCHING_CATEGORY = "FETCHING_CATEGORY"; 
export const FETCHED_OUTFITS = "FETCHED_OUTFITS"; 
export const CREATING_OUTFITS = "CREATING_OUTFITS"; 
export const CREATED_OUTFIT = "CREATED_OUTFIT"; 
export const SELECT_ITEM = "SELECT_ITEM"; 
export const REPLACE_ITEM = "REPLACE_ITEM"; 
export const SET_CURRENT_USER = "SET_CURRENT_USER"; 
export const AUTHENTICATING_USER = "AUTHENTICATING_USER"; 
export const AUTHENTICATED_USER = "AUTHENTICATED_USER"; 
export const FAILED_LOGIN = "FAILED_LOGIN"; 
export const CLOUDINARY_OPEN = "CLOUDINARY_OPEN"; 
export const PICTURE_TO_ADD = "PICTURE_TO_ADD"; 
export const INCREASE_TIMES_WORN = "INCREASE_TIMES_WORN"; 
export const DESELECT_ITEM = "DESELECT_ITEM"; 
export const UPDATED_OUTFITS = "UPDATED_OUTFITS"; 
export const LOGOUT_USER = "LOGOUT_USER"; 
export const FETCHED_LISTINGS = "FETCHED_LISTINGS";
export const FETCHING_LISTINGS = "FETCHING_LISTINGS"; 
export const SELECT_LISTING = "SELECT_LISTING"; 

export const donationLocations = [{name: "Salvation Army", latitude: 40.732953, longitude: 73.990442}, {name: "Salvation Army", latitude: 40.732953, longitude: 73.990442}, {name: "Salvation Army", latitude: 40.732953, longitude: 73.990442}]
